branch-defaults:
  39-ebcli:
    environment: ColonyCounter-dev
    group_suffix: null
global:
  application_name: ColonyCounter
  branch: null
  default_ec2_keyname: 442key
  default_platform: Python 3.4 (Preconfigured - Docker)
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
